spring.application.name=filme

# SPRING CONFIG PROPERTIES
spring.config.import=optional:file:.env[.properties]
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.batch.job.enabled=false
logging.file.name=logs/app.log

# Enable the SCRIPT.SQL for DATABASE
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=${SQL_DATABASE_URL}
spring.datasource.username=${SQL_DATABASE_USERNAME}
spring.datasource.password=${SQL_DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.forward-headers-strategy=framework


jwt.secret.key=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}



